spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://mysqldb:3306/SBMS27
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
